categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'maint'
change-template: '- $TITLE (#$NUMBER) -- @$AUTHOR'
template: |
  ## Changes
  $CHANGES

  ## Contributors
  $CONTRIBUTORS
  ---
  Previous Tag: $PREVIOUS_TAG