name: PR Labeler
on: 
  pull_request:
    types: [opened]

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
    - uses: TimonVS/pr-labeler-action@v1.0.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
